spring:
  sql:
    init:
      mode: ALWAYS
  application:
    name: spring-boot-docker
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: false    
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    url:  ${SPRING_DATASOURCE_URL:jdbc:postgresql://stagingdb:5432/bookdb}
    hikari:
      poolName: Hikari
      auto-commit: false