server:
  port: 8090

spring:
  sql:
    init:
      mode: ALWAYS
  config:
    activate:
      on-profile: staging
  datasource:
    url:  ${SPRING_DATASOURCE_URL:jdbc:postgresql://stagingdb:5432/bookdb}